export const ENABLE_EDIT_PASSWORD_MODE = 'ENABLE_EDIT_PASSWORD_MODE'
export const DISABLE_EDIT_PASSWORD_MODE = 'DISABLE_EDIT_PASSWORD_MODE'
export const COMPLETE_UPDATE_PASSWORD = 'COMPLETE_UPDATE_PASSWORD';