export const ENABLE_EDIT_PROFILE_MODE = 'ENABLE_EDIT_PROFILE_MODE'
export const DISABLE_EDIT_PROFILE_MODE = 'DISABLE_EDIT_PROFILE_MODE'

export const ENABLE_EDIT_PASSWORD_MODE = 'ENABLE_EDIT_PASSWORD_MODE'
export const DISABLE_EDIT_PASSWORD_MODE = 'DISABLE_EDIT_PASSWORD_MODE'
export const COMPLETE_UPDATE_PASSWORD = 'COMPLETE_UPDATE_PASSWORD'

export const SHOW_REQUIRED_EMAIL_CONFIRMATION_MODAL = 'SHOW_REQUIRED_EMAIL_CONFIRMATION_MODAL'
export const HIDE_REQUIRED_EMAIL_CONFIRMATION_MODAL = 'HIDE_REQUIRED_EMAIL_CONFIRMATION_MODAL'
export const SET_ACCOUNT_USER = 'SET_ACCOUNT_USER'
