export const ENABLE_EDIT_PROFILE_MODE = 'ENABLE_EDIT_PROFILE_MODE'
export const DISABLE_EDIT_PROFILE_MODE = 'DISABLE_EDIT_PROFILE_MODE'

export const ENABLE_EDIT_AVATAR = 'ENABLE_EDIT_AVATAR'
export const DISABLE_EDIT_AVATAR = 'DISABLE_EDIT_AVATAR'

export const AVATAR_SELECTED = 'AVATAR_SELECTED'
export const AVATAR_DESELECTED = 'AVATAR_DESELECTED'

export const UPDATE_PASSWORD_SUCCESSFULLY = 'UPDATE_PASSWORD_SUCCESSFULLY'
export const RESET_UPDATE_PASSWORD_FORM = 'RESET_UPDATE_PASSWORD_FORM'
export const CLEAR_PASSWORD_ERRORS = 'CLEAR_PASSWORD_ERRORS'

export const ENABLE_EDIT_PASSWORD_MODE = 'ENABLE_EDIT_PASSWORD_MODE'
export const DISABLE_EDIT_PASSWORD_MODE = 'DISABLE_EDIT_PASSWORD_MODE'
export const COMPLETE_UPDATE_PASSWORD = 'COMPLETE_UPDATE_PASSWORD'

export const SHOW_REQUIRED_EMAIL_CONFIRMATION_MODAL = 'SHOW_REQUIRED_EMAIL_CONFIRMATION_MODAL'
export const HIDE_REQUIRED_EMAIL_CONFIRMATION_MODAL = 'HIDE_REQUIRED_EMAIL_CONFIRMATION_MODAL'
export const SET_ACCOUNT_USER = 'SET_ACCOUNT_USER'
export const FETCH_USER_ACCOUNT = 'FETCH_USER_ACCOUNT'
