export const PERIOD_TYPES = ["hour", "day", "week", "month"]
export const CURRENCIES = ['vnd', 'usd', 'yen']

export const FETCH_COURSES = 'FETCH_COURSES'
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS'
export const FETCH_COURSES_FAIL = 'FETCH_COURSES_FAIL'

export const FETCH_PUBLIC_COURSE_SUCCESSFULLY = 'FETCH_PUBLIC_COURSE_SUCCESSFULLY'
export const FETCH_PUBLIC_COURSE_FAIL = 'FETCH_PUBLIC_COURSE_FAIL'

export const FETCH_PUBLIC_COURSE_SECTIONS_SUCCESSFULLY = 'FETCH_PUBLIC_COURSE_SECTIONS_SUCCESSFULLY'
export const FETCH_PUBLIC_COURSE_SECTIONS_FAIL = 'FETCH_PUBLIC_COURSE_SECTIONS_FAIL'

export const FETCH_PUBLIC_COURSE_TUTOR_SUCCESSFULLY = 'FETCH_PUBLIC_COURSE_TUTOR_SUCCESSFULLY'
export const FETCH_PUBLIC_COURSE_TUTOR_FAIL = 'FETCH_PUBLIC_COURSE_TUTOR_FAIL'
