export const FETCH_CATEGORIES_SUCCESSFULLY = "FETCH_CATEGORIES_SUCCESSFULLY"
export const FETCH_LOCATIONS_SUCCESSFULLY = "FETCH_LOCATIONS_SUCCESSFULLY"
export const RELOAD_COURSE_LEVELS = "RELOAD_COURSE_LEVELS"
export const SELECT_COURSE_LOCATIONS = "SELECT_COURSE_LOCATIONS"