export const CREATE_SUCCESSFULLY = 'CREATE_SUCCESSFULLY'
export const CREATE_COURSE_FAILED = 'CREATE_COURSE_FAILED'

export const UPDATE_SUCCESSFULLY = 'UPDATE_SUCCESSFULLY'
export const UPDATE_COURSE_FAILED = 'UPDATE_COURSE_FAILED'