export const SHOW_DASHBOARD_TUTOR_NEW_WORK_EXPERIENCE_FORM = 'SHOW_DASHBOARD_TUTOR_NEW_WORK_EXPERIENCE_FORM';
export const HIDE_DASHBOARD_TUTOR_NEW_WORK_EXPERIENCE_FORM = 'HIDE_DASHBOARD_TUTOR_NEW_WORK_EXPERIENCE_FORM';
export const CREATE_WORK_EXPERIENCE = 'CREATE_WORK_EXPERIENCE';
export const FETCH_WORK_EXPERIENCE_LIST = 'FETCH_WORK_EXPERIENCE_LIST';
export const DELETE_WORK_EXPERIENCE_ITEM = 'DELETE_WORK_EXPERIENCE_ITEM';
export const SHOW_EDIT_WORK_EXPERIENCE_FORM = 'SHOW_EDIT_WORK_EXPERIENCE_FORM';
export const HIDE_EDIT_WORK_EXPERIENCE_FORM = 'HIDE_EDIT_WORK_EXPERIENCE_FORM';
export const UPDATE_TUTOR_WORK_EXPERIENCE_ITEM = 'UPDATE_TUTOR_WORK_EXPERIENCE_ITEM';
