export const SHOW_DASHBOARD_TUTOR_NEW_EDUCATION_FORM = 'SHOW_DASHBOARD_TUTOR_NEW_EDUCATION_FORM';
export const HIDE_DASHBOARD_TUTOR_NEW_EDUCATION_FORM = 'HIDE_DASHBOARD_TUTOR_NEW_EDUCATION_FORM';
export const CREATE_EDUCATION = 'CREATE_EDUCATION';
export const FETCH_EDUCATION_LIST = 'FETCH_EDUCATION_LIST';
export const DELETE_EDUCATION_ITEM = 'DELETE_EDUCATION_ITEM';
export const SHOW_EDIT_EDUCATION_FORM = 'SHOW_EDIT_EDUCATION_FORM';
export const HIDE_EDIT_EDUCATION_FORM = 'HIDE_EDIT_EDUCATION_FORM';
export const UPDATE_TUTOR_EDUCATION_ITEM = 'UPDATE_TUTOR_EDUCATION_ITEM';
