export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_NOTIFICATION_USER = 'FETCH_NOTIFICATION_USER';
export const FETCH_TUTOR_DATA = 'FETCH_TUTOR_DATA';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const SIGN_OUT = 'SIGN_OUT';
