export const FETCH_TEACHER_CATEGORY = 'FETCH_TEACHER_CATEGORY'
export const FETCH_TEACHER_CATEGORY_SUCCESS = 'FETCH_TEACHER_CATEGORY_SUCCESS'
export const FETCH_TEACHER_CATEGORY_FAIL = 'FETCH_TEACHER_CATEGORY_FAIL'

export const FETCH_TEACHERS = 'FETCH_TEACHERS'
export const FETCH_TEACHERS_SUCCESS = 'FETCH_TEACHERS_SUCCESS'
export const FETCH_TEACHERS_FAIL = 'FETCH_TEACHERS_FAIL'


export const FETCH_MORE_TEACHERS = 'FETCH_MORE_TEACHERS'
export const FETCH_MORE_TEACHERS_SUCCESS = 'FETCH_MORE_TEACHERS_SUCCESS'
export const FETCH_MORE_TEACHERS_FAIL = 'FETCH_MORE_TEACHERS_FAIL'
export const FETCH_MORE_TEACHERS_ENDED = 'FETCH_MORE_TEACHERS_ENDED'
