export const SET_FACEBOOK_LOGIN_RESPONSE = 'SET_FACEBOOK_LOGIN_RESPONSE';
export const SET_GOOGLE_LOGIN_RESPONSE = 'SET_GOOGLE_LOGIN_RESPONSE';
export const SET_3RD_LOGIN_ERROR_RESPONSE = 'SET_3RD_LOGIN_ERROR_RESPONSE';
export const RESET_3RD_LOGIN_FORM = 'RESET_3RD_LOGIN_FORM';
export const SHOW_ROLE_SELECTION_FORM = 'SHOW_ROLE_SELECTION_FORM';
