export const FETCH_TUTOR_SUCCESS = 'FETCH_TUTOR_SUCCESS'
export const FETCH_TUTOR_FAILED = 'FETCH_TUTOR_FAILED'
export const UPDATE_TUTOR_SUCCESS = 'UPDATE_TUTOR_SUCCESS'
export const UPDATE_TUTOR_FAILED = 'UPDATE_TUTOR_FAILED'