export const SHOW_FOOTER = "SHOW_FOOTER";
export const HIDE_FOOTER = "HIDE_FOOTER";
export const STETCH_FULL = "STETCH_FULL";
export const STETCH_AUTO = "STETCH_AUTO";


//Student
export const UNSTARTED_COURSE = "not_started";
export const STARTED_COURSE = "started";
export const TERMINATED_COURSE = "finished";



//Payment
export const PAYMENT_HISTORY_PAGINATION_MAX_ITEM_PER_PAGE = 10;       //Default: 20
export const PAYMENT_HISTORY_PAGINATION_MAX_NUMBER_DISPLAY_PAGE = 5;  //Default: 5

// placeholder type
export const COURSE_DETAILS_PLACEHOLDER = "COURSE_DETAILS_PLACEHOLDER";
export const LESSON_DETAILS_PLACEHOLDER = "LESSON_DETAILS_PLACEHOLDER";
export const USER_DETAILS_PLACEHOLDER = "USER_DETAILS_PLACEHOLDER";
export const COURSE_ITEM_PLACEHOLDER = "COURSE_ITEM_PLACEHOLDER";
