export const ENABLE_EDIT_STUDENT_PROFILE_MODE = 'ENABLE_EDIT_STUDENT_PROFILE_MODE'
export const DISABLE_EDIT_STUDENT_PROFILE_MODE = 'DISABLE_EDIT_STUDENT_PROFILE_MODE'
export const ENABLE_EDIT_STUDENT_EDUCATION_MODE = 'ENABLE_EDIT_STUDENT_EDUCATION_MODE'
export const DISABLE_EDIT_STUDENT_EDUCATION_MODE = 'DISABLE_EDIT_STUDENT_EDUCATION_MODE'
export const ENABLE_EDIT_STUDENT_PASSWORD_MODE = 'ENABLE_EDIT_STUDENT_PASSWORD_MODE'
export const DISABLE_EDIT_STUDENT_PASSWORD_MODE = 'DISABLE_EDIT_STUDENT_PASSWORD_MODE'
export const SHOW_REQUIRED_EMAIL_CONFIRMATION_MODAL = 'SHOW_REQUIRED_EMAIL_CONFIRMATION_MODAL'
export const HIDE_REQUIRED_EMAIL_CONFIRMATION_MODAL = 'HIDE_REQUIRED_EMAIL_CONFIRMATION_MODAL'
export const SET_ACCOUNT_USER = 'SET_ACCOUNT_USER'
export const SET_ACCOUNT_STUDENT = 'tutor_account_SET_ACCOUNT_STUDENT'
export const UPDATE_STUDENT_EDU = 'tutor_account_UPDATE_STUDENT_EDU';

export const genders = [['M', 'male'], ['F', 'female']]
